-- CreateTable
CREATE TABLE "COUNTER" (
    "CounterID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "CounterNumber" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "SERVICE" (
    "ServiceID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "AvgServiceTime" INTEGER NOT NULL
);

-- CreateTable
CREATE TABLE "COUNTER_SERVICE" (
    "CounterID" INTEGER NOT NULL,
    "ServiceID" INTEGER NOT NULL,

    PRIMARY KEY ("CounterID", "ServiceID"),
    CONSTRAINT "COUNTER_SERVICE_CounterID_fkey" FOREIGN KEY ("CounterID") REFERENCES "COUNTER" ("CounterID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "COUNTER_SERVICE_ServiceID_fkey" FOREIGN KEY ("ServiceID") REFERENCES "SERVICE" ("ServiceID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "TICKET" (
    "TicketID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "StartTime" DATETIME NOT NULL,
    "EndTime" DATETIME NOT NULL,
    "Date" DATETIME NOT NULL,
    "ServiceID" INTEGER NOT NULL,
    CONSTRAINT "TICKET_ServiceID_fkey" FOREIGN KEY ("ServiceID") REFERENCES "SERVICE" ("ServiceID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "COUNTER_CounterNumber_key" ON "COUNTER"("CounterNumber");
